module.exports.User = require('./user.model').User
module.exports.Admins = require('./admins.model').Admins
module.exports.adminRoles = require('./admin_roles.model').adminRoles
module.exports.SideBarMenu = require('./sidebarmenu.model').SideBarMenu
module.exports.cuisines = require('./cuisines.model').cuisines
module.exports.zones = require('./zones.model').zones;
module.exports.Permission = require('./permission.model').Permission
module.exports.Restaurants = require('./restaurants.model').Restaurants
module.exports.Categories = require('./categories.model').Categories
module.exports.Subcategories = require('./subCategories.model').Subcategories
module.exports.SubSubcategory = require('./subSubcategory.model').SubSubcategory
module.exports.Addons = require('./addons.model').Addons
module.exports.Vendors = require('./vendors.model').Vendors
module.exports.Products = require('./products.model').Products
module.exports.Brands = require('./brands.model').Brands
module.exports.Parts = require('./parts.model').Parts
module.exports.Variants = require('./variants.model').Variants
module.exports.VariantCategory = require('./variants.model').VariantCategory
module.exports.VariantSubCategory = require('./variants.model').VariantSubCategory
module.exports.VariantSubSubCategory = require('./variants.model').VariantSubSubCategory
// module.exports.FittingSize = require('./fittingSizes.model').FittingSize
module.exports.Thread = require('./threads.model').Thread
module.exports.Materials = require('./materials.model').Materials
module.exports.Supplier = require('./supplier.model').Supplier
module.exports.StateTin = require('./stateTin.model').StateTin
module.exports.PurchaseOrder = require('./purchaseOrders.model').PurchaseOrder
module.exports.PurchaseOrderItem = require('./purchaseOrderItem.model').PurchaseOrderItem
module.exports.PurchaseOrderBill = require('./purchaseOrderBill.model').PurchaseOrderBill
module.exports.PurchaseOrderBillItem = require('./purchaseOrderBillItem.model').PurchaseOrderBillItem
module.exports.Design = require('./design.model').Design
module.exports.FittingThreads = require('./fittingThreads.model').FittingThreads
module.exports.HoseDashSize = require('./hosedashSize.model').HoseDashSize
module.exports.FittingDashSize = require('./fittingdashsize.model').FittingDashSize
module.exports.BendAngle = require('./bendAngle.model').BendAngle
module.exports.HoseType = require('./hosetype.model').HoseType
module.exports.BrandLayLine = require('./brandLayLaine.model').BrandLayLine
module.exports.Inventory = require('./inventory.model').Inventory
module.exports.StockMaintenance = require('./stock_maintenance.model').StockMaintenance
module.exports.Batch = require('./batch.model').Batch
module.exports.Country = require('./country.model').Country
module.exports.States = require('./state.model').States
module.exports.City = require('./cities.model').City
module.exports.Customer = require('./customer.model').Customer
module.exports.SaleOrder = require('./saleOrders.model').SaleOrder
module.exports.SaleOrderItem = require('./saleOrderItems.model').SaleOrderItem
module.exports.BatchAllocation = require('./batchAllocation.model').BatchAllocation
module.exports.StockArchive = require('./stockArchive.model').StockArchive
module.exports.ProductCodeCounter = require('./productCodeCounter.model').ProductCodeCounter
module.exports.ProductionSheetDetails = require('./productionSheetDetails.model').ProductionSheet
module.exports.ProductionSheetItem = require('./productionSheetItems.model').ProductionSheetItem
module.exports.SheetNumberCounter = require('./sheetNumberCounter.model').SheetNumberCounter
module.exports.ProductionProcess = require('./productionProcess.model').ProductionProcess
module.exports.ProductionProcessItem = require('./productionProcessItems.model').ProductionProcessItem
module.exports.ProductionProcessLog = require('./produtionProcessLogs.model').ProductionProcessLog
module.exports.ProductionProcessItemLogs = require('./productionProcessItemsLog.model').ProductionProcessItemLog
module.exports.Operator = require('./operator.model').Operator
// module.exports. = require('./').
// module.exports. = require('./').
// module.exports. = require('./').



// module.exports.Clients = require('./clients.model').Clients


